[ Feature & Refactoring ] BottomSheet 제작 & Toast 개선
DDu-Du-DDu-Du/DDuDu_Front pull request #5
Opened 2024-05-04 12:04 UTC by Jae0o

ㅎ.. 죄송합니다 하루종일 작업했는데 알고보니 하나의 브랜치에서 작업했지뭐람... 🤦 이번에만 봐주세요 ㅎ ❤️

# Toast 개선

Toast 개선

[🔗 Storybook](https://6633bd85fb75146bc1604a73-yigqyluepr.chromatic.com/)

## ✅ PR 유형

- [x] 코드 리팩토링

## 💻 작업 내용

기존 Context API를 사용하던 Toast 방식을 전역 상태관리인 Zustand를 활용하는 방향으로 변경하였습니다.
- Toast 의 특성상 **반드시 App의 최상단에 존재해야하기 때문에 전역 상태관리인 Zustnad를 활용할 수 있다고 판단**하였습니다.
- Context API보다는 성능 최적화가 더 잘되어있는 `Zustand`를 활용하는 방향이 좋다고 생각하였습니다.

- `useToast` hook을 별도로 분리하지 않고 `useToastStore`를 활용할 수 있지만,<br> useToastStore내부의 `toastList`, `removeToast`를 다른 Component에서 꺼낼 수 없기를 원했습니다. <br> 따라서 useTaost를 통해 `createToast`만 사용하는곳에서 꺼내 사용할 수 있도록 하기위해 `useToast`를 별도로 제작하였습니다.

<br>
<br>
<br>
<br>
<br>

# Bottom Sheet 제작

BottomSheet 제작하기

- Storybook에서 viewport 와 body를 제어할 수 없어 BottomSheet적용이 불가능하여 제외하였습니다.

대신 해당 브랜치에서 테스트할 수 있도록 환경을 만들어놓았습니다.

```
git fetch
git checkout TS-225/bottom_sheet
```

## ✅ PR 유형

- [x] 새로운 기능 추가

## 💻 작업 내용

Props
- children : Bottom Sheet 내부에 전달됩니다.
- isShow : Bottom Sheet가 오픈될지에 대한 `boolean`값을 전달받습니다.
- onClose : useBottomSheet hook을 사용하는 경우 외부 상태를 변경할 수 있는 `handleCloseSheet` 메서드를 전달받습니다.

<br>

- defaultHeight ? : Bottom Sheet가 나타나는 가장 중간 위치의 값을 전달받습니다. ("50rem" , px 등으로 전달 가능 ) - `default : "35dvh"`
- maxHeight : Bottom Sheet가 펼쳐질수 있는 최대 값을 전달받습니다. ("60%" , px 등으로 전달 가능 ) - `default : "80dvh"`

<br>

🔥 Storybook에서는 `viewport`값을 제대로 사용할 수 없어 BottomSheet동작이 원활하지 임시로 제외하였습니다.

<br>

BottomSheet를 2가지 방법으로 사용할 수 있습니다.
- 버튼 클릭 혹은 특정 조건을 통해 BottomSheet가 오픈되는 경우를 고려하여 `useBottomSheet` hook을 통해 제어할 수 있도록 구현하였습니다.<br> hook을 이용하는 경우 onClose 속성에 `handleCloseSheet` 메서드를 isShow 속성에 `isShow`값을 전달해야합니다.

- 항상 BottomSheet가 존재하는 경우를 고려하여 isShow값에 `true`를 전달하면 BottomSheet가 사라지지않고 존재하도록 제작하였습니다.

## 💬 PR 포인트

2024-05-04 17:01 UTC, Jaeppetto requested changes
고봉밥 커밋.. 배부르게 먹었습니다 🥹 Toast도 더 직관적으로 개선된 것 같고, BottomSheet 로직의 짜임새가 너~무 잘 짜여진 것 같아요. 커스텀훅 패턴 너무 좋네요.. 킹갓재영..

모바일 드래깅 이벤트만 한 번 확인 부탁드립니다! 아이폰 safari에서 `맥북IP주소/포트번호` 로 접속하니 바로 테스트되더라구요. 짱 편해요..👍🏻 고생 많으셨습니다 재영뉨!

2024-05-04 17:01 UTC, Jaeppetto commented on src/app/_components/client/Toast/ToastProvider.tsx
> +  const { toastList, removeToast } = useToastStore();
오 실제로 사용될 createToast만 훅으로 분리하니 더 깔끔한 것 같네요!

2024-05-04 17:01 UTC, Jaeppetto commented on src/app/_components/client/Toast/ToastProvider.tsx
>        <ul className="absolute right-[1rem] top-[1rem] flex flex-col gap-[0.6rem] text-size14 z-toast">
`z-index`도 따로 빼놓으셨군요! 헤더 작업할 때 참고하겠습니다 👍🏻

2024-05-04 17:01 UTC, Jaeppetto commented on src/app/_components/client/Toast/store/useToastStore/useToastStore.ts
> +      }, deleteTime + 500);
ASK;

상수로 추가적인 오프셋을 주신 이유가 궁금합니다 👀

2024-05-04 17:01 UTC, Jaeppetto commented on src/app/_components/client/BottomSheet/hooks/useSheetDrag/useSheetDrag.ts
> +    return () => {
크.. 이벤트 핸들러 제거까지.. 너무 좋은 것 같습니다.

2024-05-04 17:01 UTC, Jaeppetto commented on src/app/(route)/page.tsx
> +    <main className="w-full h-[1000rem]">
ASK;

페이지 높이를 이와같이 설정하신 이유가 있을까요! 별개로 `h-full`을 적용해도 스크롤링이 되네요....?! 최상단 HTML의 높이가 100dvh로 알고 있는데 😅

2024-05-04 17:01 UTC, Jaeppetto commented on src/app/_components/client/BottomSheet/BottomSheet.tsx
> +            <BottomHeader
🚨 P1;

아이폰 기준 모바일 환경에서 헤더의 드래깅이 작동하지 않는 것 같습니다..! (뒤의 Home 페이지만 드래깅돼요 🥲)
아마 `onMouseDown`에 핸들러가 부착되어 있어 터치 이벤트에는 작동하지 않는 것으로 보여지는데, 확인 한 번 부탁드립니다~👍🏻

2024-05-06 02:48 UTC, Jae0o commented on src/app/_components/client/Toast/store/useToastStore/useToastStore.ts
> +      }, deleteTime + 500);
exit animation때문인데 궁금하시면 추가적으로 게더에서 알려드릴게요!

2024-05-06 02:50 UTC, Jae0o commented on src/app/(route)/page.tsx
> +    <main className="w-full h-[1000rem]">
테스트 용도입니다.

1. main 내부에 존재하는 요소들이 100dvh를 넘어간다면 스크롤되게 만들어 놓아서 스크롤이 가능합니다.
2. bottom sheet가 존재하더라도 뒷배경에 존재하는 요소들의 크기에따라 정상적으로 드래그되는지 테스트하기 위함입니다.
3. bottom sheet내부에도 height값이 큰 요소가 들어있을때 bottom sheet의 open 상태와 full open 상태의 차이를 확인하기 위해서 대부분의 크기를 크게하였습니다.

2024-05-06 02:51 UTC, Jae0o commented on src/app/_components/client/BottomSheet/BottomSheet.tsx
> +            <BottomHeader
오... 맞네요. 바로 적용하겠습니다

2024-05-06 06:19 UTC, Jae0o commented on src/app/_components/client/BottomSheet/BottomSheet.tsx
> +            <BottomHeader
적용 완료했습니다

2024-05-06 06:20 UTC, SeungHyune approved these changes
재영님 고생 많으셨습니다 ~ 😊
리뷰 한번 확인 부탁드리겠습니다 ㅎㅎ

스크럼 때 Bottom Sheet Framer Motion 관련 로직 설명 한번만 해주시면 좋을 것 같습니다 !!

2024-05-06 06:20 UTC, SeungHyune commented on src/app/_components/client/Toast/ToastProvider.tsx
[ P5 ]
toast 컴포넌트 구현을 잘 해주신 것 같습니다 !! 👍
한 가지 궁금한 점은 지금과 같이 `<ul>` 태그를 `Provider`로 감싸서 최상단에서 사용하게 됐을 때 **`toastList`가 없는 경우에도 계속해서 `<ul>` 태그가 html에 렌더링** 될 것 같은데 이러한 부분이 주는 단점도 있을 것 같습니다.

**`toastList.length`가 있을 때만 `ul` 태그를 렌더링 하는 조건을 추가**해주는 것은 어떨까요 ?! 🧐👀

2024-05-06 06:20 UTC, SeungHyune commented on src/app/_components/client/BottomSheet/hooks/useSheetAnimationState/useSheetAnimationState.ts
> +  }, [isShow]);
[ P5 ]
`useEffect`가 없으면 동작하지 않는 이유가 있는 건가요 ??!
초깃값으로 `isShow`를 가져오는 거 같은데 따로 어떤 부분에서 필요한 지 이해가 가지 않네요 ㅠㅠ 😢

2024-05-06 06:20 UTC, SeungHyune commented on src/app/_components/client/BottomSheet/hooks/useSheetAction/useSheetAction.ts
> +    (event: ReactMouseEvent<HTMLElement> | ReactTouchEvent<HTMLElement>) => {
[ P3 ]
`handleStartAction`, `handleMovieAction`, `handleEndAction` 함수의 전달된 event에 대한 타입명이 다른데 서로 다르게 작성된 이유가 있을까요 ??!

그게 아니라면 통일 시켜줘도 좋을 것 같습니다 !! 😊

2024-05-06 06:20 UTC, SeungHyune commented on src/app/_components/client/BottomSheet/components/BottomHeader/BottomHeader.tsx
> +        />
[ ASK ]
`animate`에 들어간 `draggingState`에 따라 어떻게 달라지는 건가요 ?!
데일리 스크럼 때 한번 설명해 주시면 좋을 것 같아요 ~~ ㅎㅎ 😁

2024-05-06 09:51 UTC, Jae0o commented on src/app/_components/client/Toast/ToastProvider.tsx
좋은 방법일것 같기도 한데 조심스러운 부분은 어느 비용이 더 적게 들까요?

1. 리스트에 Item이 생기면 지우고 생기면 다시 Element를 새롭게 다시 그려줘야하는 비용
2. 지속해서 존재하는 Element
이 부분이 조심스럽네요

2024-05-06 09:52 UTC, Jae0o commented on src/app/_components/client/BottomSheet/hooks/useSheetAnimationState/useSheetAnimationState.ts
> +  }, [isShow]);
사라지는 exit animation때문에 두개의 상태가 존재합니다.

해당 부분에 대해서 더 궁금하시다면 스크럼때 한번 설명드릴게요

2024-05-06 09:53 UTC, Jae0o commented on src/app/_components/client/BottomSheet/hooks/useSheetAction/useSheetAction.ts
> +    (event: ReactMouseEvent<HTMLElement> | ReactTouchEvent<HTMLElement>) => {
전부 다른 Type입니다!

제가 별도로 별칭을 지어서 붙여준 ReactMouseEvent는 React에서 JSX에서 사용하기 위한 Event Type이고

그냥 사용하고있는 MouseEvent는 JS 자체에서 사용되어지는 Type입니다.

2024-05-06 10:00 UTC, Jae0o commented on src/app/_components/client/BottomSheet/components/BottomHeader/BottomHeader.tsx
> +        />
framer motion 사용 방법으로 아래 center up down이 들어가서 각각에 맞는 애니메이션이 실행됩니다.

2024-05-06 14:30 UTC, Jaeppetto commented on src/app/_components/client/BottomSheet/BottomSheet.tsx
> +            <BottomHeader
@Jae0o 재영님 혹시 모바일 환경에서 테스트해보셨을까요..! 토글 버튼 눌러도 바텀시트가 올라오지 않는 것 같습니다.

2024-05-07 02:15 UTC, Jae0o commented on src/app/_components/client/BottomSheet/BottomSheet.tsx
> +            <BottomHeader
전 잘되긴하는데 의심가는 코드가 있어서 제거했습니다.

2024-05-07 06:04 UTC, Songhee99 approved these changes
결과도 그렇고 코드도 그렇고 진짜 최고입니다...👍🏻👍🏻 
아까 설명해주셔서 코드 훑는데 더 도움이 되었습니다 ㅎㅎ 감사해요 🙇🏻‍♀️

2024-05-07 08:02 UTC, Jaeppetto approved these changes

2024-05-07 08:13 UTC, merged